GET http://localhost:3003/api/blogs

###

POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title":"something",
    "author":"something",
    "url":"something",
    "likes":1,
    "userId":"67aafa4acffc511f8df723d5"
}

###

POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username":"root",
    "name": "sanchit",
    "password": "sanchit33"

}

###
GET http://localhost:3003/api/users